version: '3.7'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app:latest # Add this to specify the image tag
    ports:
      - "80:80"
    container_name: react-app # Name the container for easier management
